In [ ]:
import numpy as np
import pandas as pd
import torch
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.preprocessing import LabelEncoder

In [ ]:
df = pd.read_csv('https://raw.githubusercontent.com/gscdit/Breast-Cancer-Detection/refs/heads/master/data.csv')
df.head()

,id,diagnosis,radius_mean,texture_mean,perimeter_mean,area_mean,smoothness_mean,compactness_mean,concavity_mean,concave points_mean,...,texture_worst,perimeter_worst,area_worst,smoothness_worst,compactness_worst,concavity_worst,concave points_worst,symmetry_worst,fractal_dimension_worst,Unnamed: 32
0,842302,M,17.99,10.38,122.80,1001.0,0.11840,0.27760,0.3001,0.14710,...,17.33,184.60,2019.0,0.1622,0.6656,0.7119,0.2654,0.4601,0.11890,NaN
1,842517,M,20.57,17.77,132.90,1326.0,0.08474,0.07864,0.0869,0.07017,...,23.41,158.80,1956.0,0.1238,0.1866,0.2416,0.1860,0.2750,0.08902,NaN
2,84300903,M,19.69,21.25,130.00,1203.0,0.10960,0.15990,0.1974,0.12790,...,25.53,152.50,1709.0,0.1444,0.4245,0.4504,0.2430,0.3613,0.08758,NaN
3,84348301,M,11.42,20.38,77.58,386.1,0.14250,0.28390,0.2414,0.10520,...,26.50,98.87,567.7,0.2098,0.8663,0.6869,0.2575,0.6638,0.17300,NaN
4,84358402,M,20.29,14.34,135.10,1297.0,0.10030,0.13280,0.1980,0.10430,...,16.67,152.20,1575.0,0.1374,0.2050,0.4000,0.1625,0.2364,0.07678,NaN

In [ ]:
df.shape

(569, 33)

In [ ]:
df.drop(columns=['id', 'Unnamed: 32'], inplace= True)

In [ ]:
df.head()

,diagnosis,radius_mean,texture_mean,perimeter_mean,area_mean,smoothness_mean,compactness_mean,concavity_mean,concave points_mean,symmetry_mean,...,radius_worst,texture_worst,perimeter_worst,area_worst,smoothness_worst,compactness_worst,concavity_worst,concave points_worst,symmetry_worst,fractal_dimension_worst
0,M,17.99,10.38,122.80,1001.0,0.11840,0.27760,0.3001,0.14710,0.2419,...,25.38,17.33,184.60,2019.0,0.1622,0.6656,0.7119,0.2654,0.4601,0.11890
1,M,20.57,17.77,132.90,1326.0,0.08474,0.07864,0.0869,0.07017,0.1812,...,24.99,23.41,158.80,1956.0,0.1238,0.1866,0.2416,0.1860,0.2750,0.08902
2,M,19.69,21.25,130.00,1203.0,0.10960,0.15990,0.1974,0.12790,0.2069,...,23.57,25.53,152.50,1709.0,0.1444,0.4245,0.4504,0.2430,0.3613,0.08758
3,M,11.42,20.38,77.58,386.1,0.14250,0.28390,0.2414,0.10520,0.2597,...,14.91,26.50,98.87,567.7,0.2098,0.8663,0.6869,0.2575,0.6638,0.17300
4,M,20.29,14.34,135.10,1297.0,0.10030,0.13280,0.1980,0.10430,0.1809,...,22.54,16.67,152.20,1575.0,0.1374,0.2050,0.4000,0.1625,0.2364,0.07678

### train test split

In [ ]:
X_train, X_test, y_train, y_test = train_test_split(df.iloc[:, 1:], df.iloc[:, 0], test_size=0.2)

### scaling

In [ ]:
scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

In [ ]:
X_train

array([[-1.34033451,  0.40755172, -1.32260515, ..., -0.72818188,
        -0.0309949 ,  0.47647236],
       [ 1.12687964,  1.21479668,  0.99855431, ...,  0.01214278,
        -0.63083589, -0.2187113 ],
       [ 0.47983706, -1.23950716,  0.44238613, ...,  0.37596122,
        -0.2795921 , -0.70143187],
       ...,
       [-0.61896947, -0.23684844, -0.66531549, ..., -0.76196502,
        -0.18015322, -0.51593947],
       [-0.16429091, -1.52332239, -0.24481864, ..., -1.38657096,
        -1.01094903, -1.18525328],
       [-0.68600542, -0.60208607, -0.7070281 , ..., -0.65923981,
        -1.9010874 , -0.55171694]])

In [ ]:
y_train

66     B
274    M
133    B
548    B
538    B
      ..
428    B
282    M
52     B
308    B
136    B
Name: diagnosis, Length: 455, dtype: object

### Label Encoding

In [ ]:
encoder = LabelEncoder()
y_train = encoder.fit_transform(y_train)
y_test = encoder.transform(y_test)

In [ ]:
y_train

array([0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 1, 1, 1, 1, 1,
       1, 0, 0, 0, 0, 1, 1, 0, 0, 1, 1, 0, 0, 0, 1, 0, 1, 0, 1, 0, 1, 1,
       1, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0,
       0, 1, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 1, 0,
       1, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0,
       0, 0, 0, 1, 1, 0, 1, 0, 0, 1, 1, 0, 0, 0, 1, 0, 1, 1, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 1,
       0, 1, 1, 1, 0, 1, 0, 0, 0, 1, 1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1,
       1, 1, 0, 0, 0, 0, 0, 1, 0, 1, 1, 0, 1, 1, 0, 1, 0, 0, 0, 1, 1, 0,
       0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 1, 0, 0, 1, 0, 0, 0, 0,
       0, 0, 1, 0, 1, 1, 0, 0, 0, 0, 1, 1, 1, 0, 1, 1, 1, 0, 0, 0, 0, 0,
       0, 1, 0, 0, 0, 0, 1, 1, 1, 1, 1, 0, 0, 0, 1, 0, 0, 0, 0, 1, 1, 0,
       1, 0, 0, 1, 0, 1, 1, 1, 1, 0, 0, 0, 1, 0, 1, 1, 1, 1, 0, 1, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 1, 0, 0, 0, 0, 0, 0,
       0, 0, 1, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 0, 0, 1, 0, 0, 1, 0,
       0, 1, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1,
       0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0, 1, 0, 1, 1, 0,
       0, 0, 0, 0, 0, 1, 0, 1, 1, 0, 0, 0, 1, 1, 1, 1, 1, 0, 0, 1, 0, 0,
       0, 1, 1, 0, 1, 0, 1, 0, 1, 0, 0, 0, 1, 1, 0, 1, 1, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 1, 1, 1, 1, 0, 1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 1,
       0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0])

### Numpy arrays to PyTorch tensors

In [ ]:
X_train_tensor = torch.from_numpy(X_train.astype(np.float32))
X_test_tensor = torch.from_numpy(X_test.astype(np.float32))
y_train_tensor = torch.from_numpy(y_train.astype(np.float32))
y_test_tensor = torch.from_numpy(y_test.astype(np.float32))

In [ ]:
X_train_tensor.shape

torch.Size([455, 30])

In [ ]:
y_train_tensor.shape

torch.Size([455])

In [ ]:
from torch.utils.data import Dataset, DataLoader

class CustomDataset(Dataset):
  def __init__(self, features, labels):

    self.features = features
    self.labels = labels

  def __len__(self):
    return self.features.shape[0]

  def __getitem__(self, idx):
    return self.features[idx], self.labels[idx]

In [ ]:
train_dataset=CustomDataset(X_train_tensor,y_train_tensor)
test_dataset=CustomDataset(X_test_tensor,y_test_tensor)

In [ ]:
train_dataset[10]

(tensor([-0.3741, -0.6440, -0.4268, -0.4208,  0.1500, -0.9301, -0.6144, -0.4962,
         -0.7894, -0.8890, -0.5783, -0.6129, -0.6506, -0.4502,  0.3290, -1.0779,
         -0.4913, -0.4747,  0.2100, -0.7207, -0.5732, -0.9584, -0.6331, -0.5623,
         -0.0924, -1.1046, -0.7619, -0.8253, -0.8249, -1.0653]),
 tensor(0.))

In [ ]:
train_loader=DataLoader(train_dataset,batch_size=32,shuffle=True)
test_loader=DataLoader(test_dataset,batch_size=32,shuffle=True)

### Defining the model

In [ ]:
import torch.nn as nn


class MySimpleNN(nn.Module):

  def __init__(self, num_features):

    super().__init__()
    self.linear = nn.Linear(num_features, 1)
    self.sigmoid = nn.Sigmoid()

  def forward(self, features):

    out = self.linear(features)
    out = self.sigmoid(out)

    return out

### Important Parameters

In [ ]:
learning_rate = 0.1
epochs = 25

In [ ]:
# define loss function
loss_function = nn.BCELoss()

### Training Pipeline

In [ ]:

# create model
model = MySimpleNN(X_train_tensor.shape[1])

# define optimizer
optimizer = torch.optim.SGD(model.parameters(), lr=learning_rate)

# define loop
for epoch in range(epochs):
  for batch_features, batch_labels in train_loader:

    # forward pass
    y_pred = model(X_train_tensor)


    # loss calculate
    loss = loss_function(y_pred, y_train_tensor.view(-1,1))

    # clear gradients
    optimizer.zero_grad()

    # backward pass
    loss.backward()

    # parameters update
    optimizer.step()

    # print loss in each epoch
    print(f'Epoch: {epoch + 1}, Loss: {loss.item()}')

Epoch: 1, Loss: 0.8706014156341553
Epoch: 1, Loss: 0.6364947557449341
Epoch: 1, Loss: 0.5167984962463379
Epoch: 1, Loss: 0.44579166173934937
Epoch: 1, Loss: 0.39830446243286133
Epoch: 1, Loss: 0.36391353607177734
Epoch: 1, Loss: 0.3375915586948395
Epoch: 1, Loss: 0.3166184723377228
Epoch: 1, Loss: 0.2993924617767334
Epoch: 1, Loss: 0.28490737080574036
Epoch: 1, Loss: 0.27249789237976074
Epoch: 1, Loss: 0.2617054581642151
Epoch: 1, Loss: 0.25220295786857605
Epoch: 1, Loss: 0.2437502145767212
Epoch: 1, Loss: 0.23616617918014526
Epoch: 2, Loss: 0.2293117344379425
Epoch: 2, Loss: 0.22307759523391724
Epoch: 2, Loss: 0.21737666428089142
Epoch: 2, Loss: 0.2121383398771286
Epoch: 2, Loss: 0.2073047161102295
Epoch: 2, Loss: 0.20282766222953796
Epoch: 2, Loss: 0.1986667811870575
Epoch: 2, Loss: 0.19478783011436462
Epoch: 2, Loss: 0.19116155803203583
Epoch: 2, Loss: 0.18776269257068634
Epoch: 2, Loss: 0.18456940352916718
Epoch: 2, Loss: 0.18156255781650543
Epoch: 2, Loss: 0.1787254512310028
Epoch: 2, Loss: 0.17604336142539978
Epoch: 2, Loss: 0.17350319027900696
Epoch: 3, Loss: 0.17109334468841553
Epoch: 3, Loss: 0.16880345344543457
Epoch: 3, Loss: 0.1666242629289627
Epoch: 3, Loss: 0.16454744338989258
Epoch: 3, Loss: 0.16256549954414368
Epoch: 3, Loss: 0.16067169606685638
Epoch: 3, Loss: 0.15885986387729645
Epoch: 3, Loss: 0.15712447464466095
Epoch: 3, Loss: 0.1554604470729828
Epoch: 3, Loss: 0.15386319160461426
Epoch: 3, Loss: 0.1523284912109375
Epoch: 3, Loss: 0.1508524864912033
Epoch: 3, Loss: 0.14943160116672516
Epoch: 3, Loss: 0.14806263148784637
Epoch: 3, Loss: 0.14674259722232819
Epoch: 4, Loss: 0.14546868205070496
Epoch: 4, Loss: 0.14423836767673492
Epoch: 4, Loss: 0.14304926991462708
Epoch: 4, Loss: 0.1418992131948471
Epoch: 4, Loss: 0.14078615605831146
Epoch: 4, Loss: 0.1397082358598709
Epoch: 4, Loss: 0.13866367936134338
Epoch: 4, Loss: 0.13765084743499756
Epoch: 4, Loss: 0.13666819036006927
Epoch: 4, Loss: 0.13571429252624512
Epoch: 4, Loss: 0.13478781282901764
Epoch: 4, Loss: 0.13388749957084656
Epoch: 4, Loss: 0.13301222026348114
Epoch: 4, Loss: 0.13216079771518707
Epoch: 4, Loss: 0.13133221864700317
Epoch: 5, Loss: 0.13052551448345184
Epoch: 5, Loss: 0.12973977625370026
Epoch: 5, Loss: 0.12897410988807678
Epoch: 5, Loss: 0.12822774052619934
Epoch: 5, Loss: 0.12749984860420227
Epoch: 5, Loss: 0.12678971886634827
Epoch: 5, Loss: 0.1260966658592224
Epoch: 5, Loss: 0.12542003393173218
Epoch: 5, Loss: 0.12475920468568802
Epoch: 5, Loss: 0.12411358207464218
Epoch: 5, Loss: 0.1234826147556305
Epoch: 5, Loss: 0.12286577373743057
Epoch: 5, Loss: 0.12226251512765884
Epoch: 5, Loss: 0.12167242914438248
Epoch: 5, Loss: 0.12109500914812088
Epoch: 6, Loss: 0.12052983790636063
Epoch: 6, Loss: 0.11997649073600769
Epoch: 6, Loss: 0.11943458020687103
Epoch: 6, Loss: 0.1189037337899208
Epoch: 6, Loss: 0.11838357150554657
Epoch: 6, Loss: 0.11787378787994385
Epoch: 6, Loss: 0.1173739954829216
Epoch: 6, Loss: 0.11688392609357834
Epoch: 6, Loss: 0.1164032518863678
Epoch: 6, Loss: 0.11593170464038849
Epoch: 6, Loss: 0.11546899378299713
Epoch: 6, Loss: 0.11501485109329224
Epoch: 6, Loss: 0.1145690530538559
Epoch: 6, Loss: 0.11413130909204483
Epoch: 6, Loss: 0.11370141804218292
Epoch: 7, Loss: 0.11327913403511047
Epoch: 7, Loss: 0.11286426335573196
Epoch: 7, Loss: 0.11245658248662949
Epoch: 7, Loss: 0.11205590516328812
Epoch: 7, Loss: 0.11166200786828995
Epoch: 7, Loss: 0.11127474159002304
Epoch: 7, Loss: 0.11089392006397247
Epoch: 7, Loss: 0.11051937192678452
Epoch: 7, Loss: 0.11015091091394424
Epoch: 7, Loss: 0.10978839546442032
Epoch: 7, Loss: 0.1094316691160202
Epoch: 7, Loss: 0.10908059775829315
Epoch: 7, Loss: 0.10873501747846603
Epoch: 7, Loss: 0.10839477926492691
Epoch: 7, Loss: 0.10805977880954742
Epoch: 8, Loss: 0.10772988200187683
Epoch: 8, Loss: 0.10740494728088379
Epoch: 8, Loss: 0.10708488523960114
Epoch: 8, Loss: 0.10676954686641693
Epoch: 8, Loss: 0.10645882785320282
Epoch: 8, Loss: 0.10615263134241104
Epoch: 8, Loss: 0.10585084557533264
Epoch: 8, Loss: 0.10555335879325867
Epoch: 8, Loss: 0.10526009649038315
Epoch: 8, Loss: 0.10497092455625534
Epoch: 8, Loss: 0.10468579828739166
Epoch: 8, Loss: 0.10440459102392197
Epoch: 8, Loss: 0.10412723571062088
Epoch: 8, Loss: 0.10385363548994064
Epoch: 8, Loss: 0.10358370840549469
Epoch: 9, Loss: 0.10331739485263824
Epoch: 9, Loss: 0.10305458307266235
Epoch: 9, Loss: 0.10279523581266403
Epoch: 9, Loss: 0.10253925621509552
Epoch: 9, Loss: 0.10228654742240906
Epoch: 9, Loss: 0.10203710943460464
Epoch: 9, Loss: 0.10179083049297333
Epoch: 9, Loss: 0.10154765099287033
Epoch: 9, Loss: 0.10130752623081207
Epoch: 9, Loss: 0.1010703593492508
Epoch: 9, Loss: 0.1008361428976059
Epoch: 9, Loss: 0.10060475021600723
Epoch: 9, Loss: 0.1003761738538742
Epoch: 9, Loss: 0.10015035420656204
Epoch: 9, Loss: 0.09992723912000656
Epoch: 10, Loss: 0.0997067540884018
Epoch: 10, Loss: 0.09948886930942535
Epoch: 10, Loss: 0.09927353262901306
Epoch: 10, Loss: 0.09906070679426193
Epoch: 10, Loss: 0.0988503098487854
Epoch: 10, Loss: 0.09864231944084167
Epoch: 10, Loss: 0.09843671321868896
Epoch: 10, Loss: 0.09823340177536011
Epoch: 10, Loss: 0.09803237020969391
Epoch: 10, Loss: 0.09783358126878738
Epoch: 10, Loss: 0.09763698279857635
Epoch: 10, Loss: 0.09744253754615784
Epoch: 10, Loss: 0.09725020080804825
Epoch: 10, Loss: 0.0970599502325058
Epoch: 10, Loss: 0.0968717485666275
Epoch: 11, Loss: 0.09668555110692978
Epoch: 11, Loss: 0.09650132060050964
Epoch: 11, Loss: 0.0963190421462059
Epoch: 11, Loss: 0.09613867849111557
Epoch: 11, Loss: 0.09596017748117447
Epoch: 11, Loss: 0.09578350186347961
Epoch: 11, Loss: 0.0956086665391922
Epoch: 11, Loss: 0.09543560445308685
Epoch: 11, Loss: 0.09526429325342178
Epoch: 11, Loss: 0.0950947105884552
Epoch: 11, Loss: 0.09492681175470352
Epoch: 11, Loss: 0.09476058930158615
Epoch: 11, Loss: 0.0945960059762001
Epoch: 11, Loss: 0.09443305432796478
Epoch: 11, Loss: 0.09427166730165482
Epoch: 12, Loss: 0.0941118597984314
Epoch: 12, Loss: 0.09395359456539154
Epoch: 12, Loss: 0.09379684925079346
Epoch: 12, Loss: 0.09364157915115356
Epoch: 12, Loss: 0.09348779171705246
Epoch: 12, Loss: 0.09333544224500656
Epoch: 12, Loss: 0.09318451583385468
Epoch: 12, Loss: 0.09303499758243561
Epoch: 12, Loss: 0.09288686513900757
Epoch: 12, Loss: 0.09274010360240936
Epoch: 12, Loss: 0.092594675719738
Epoch: 12, Loss: 0.09245055168867111
Epoch: 12, Loss: 0.09230773895978928
Epoch: 12, Loss: 0.0921662300825119
Epoch: 12, Loss: 0.09202595800161362
Epoch: 13, Loss: 0.09188694506883621
Epoch: 13, Loss: 0.0917491540312767
Epoch: 13, Loss: 0.09161257743835449
Epoch: 13, Loss: 0.0914771780371666
Epoch: 13, Loss: 0.0913429856300354
Epoch: 13, Loss: 0.09120994061231613
Epoch: 13, Loss: 0.09107803553342819
Epoch: 13, Loss: 0.09094724804162979
Epoch: 13, Loss: 0.09081757813692093
Epoch: 13, Loss: 0.09068901091814041
Epoch: 13, Loss: 0.09056151658296585
Epoch: 13, Loss: 0.09043509513139725
Epoch: 13, Loss: 0.09030971676111221
Epoch: 13, Loss: 0.09018538147211075
Epoch: 13, Loss: 0.09006206691265106
Epoch: 14, Loss: 0.08993977308273315
Epoch: 14, Loss: 0.08981846272945404
Epoch: 14, Loss: 0.08969812840223312
Epoch: 14, Loss: 0.0895787924528122
Epoch: 14, Loss: 0.08946038782596588
Epoch: 14, Loss: 0.08934293687343597
Epoch: 14, Loss: 0.08922642469406128
Epoch: 14, Loss: 0.08911081403493881
Epoch: 14, Loss: 0.08899614214897156
Epoch: 14, Loss: 0.08888234198093414
Epoch: 14, Loss: 0.08876943588256836
Epoch: 14, Loss: 0.08865741640329361
Epoch: 14, Loss: 0.08854623138904572
Epoch: 14, Loss: 0.08843591809272766
Epoch: 14, Loss: 0.08832644671201706
Epoch: 15, Loss: 0.08821780234575272
Epoch: 15, Loss: 0.08810997754335403
Epoch: 15, Loss: 0.08800297230482101
Epoch: 15, Loss: 0.08789676427841187
Epoch: 15, Loss: 0.0877913385629654
Epoch: 15, Loss: 0.0876867026090622
Epoch: 15, Loss: 0.08758283406496048
Epoch: 15, Loss: 0.08747972548007965
Epoch: 15, Loss: 0.0873773843050003
Epoch: 15, Loss: 0.08727577328681946
Epoch: 15, Loss: 0.08717489242553711
Epoch: 15, Loss: 0.08707475662231445
Epoch: 15, Loss: 0.0869753360748291
Epoch: 15, Loss: 0.08687663078308105
Epoch: 15, Loss: 0.08677861094474792
Epoch: 16, Loss: 0.0866812914609909
Epoch: 16, Loss: 0.0865846574306488
Epoch: 16, Loss: 0.08648870140314102
Epoch: 16, Loss: 0.08639341592788696
Epoch: 16, Loss: 0.08629877865314484
Epoch: 16, Loss: 0.08620481193065643
Epoch: 16, Loss: 0.08611150830984116
Epoch: 16, Loss: 0.08601881563663483
Epoch: 16, Loss: 0.08592676371335983
Epoch: 16, Loss: 0.08583535254001617
Epoch: 16, Loss: 0.08574453741312027
Epoch: 16, Loss: 0.08565434068441391
Epoch: 16, Loss: 0.0855647549033165
Epoch: 16, Loss: 0.08547576516866684
Epoch: 16, Loss: 0.08538735657930374
Epoch: 17, Loss: 0.0852995365858078
Epoch: 17, Loss: 0.08521230518817902
Epoch: 17, Loss: 0.0851256400346756
Epoch: 17, Loss: 0.08503954857587814
Epoch: 17, Loss: 0.08495401591062546
Epoch: 17, Loss: 0.08486903458833694
Epoch: 17, Loss: 0.084784597158432
Epoch: 17, Loss: 0.08470069617033005
Epoch: 17, Loss: 0.08461735397577286
Epoch: 17, Loss: 0.08453453332185745
Epoch: 17, Loss: 0.08445222675800323
Epoch: 17, Loss: 0.084370456635952
Epoch: 17, Loss: 0.08428917825222015
Epoch: 17, Loss: 0.08420843631029129
Epoch: 17, Loss: 0.08412819355726242
Epoch: 18, Loss: 0.08404843509197235
Epoch: 18, Loss: 0.08396917581558228
Epoch: 18, Loss: 0.08389042317867279
Epoch: 18, Loss: 0.08381213992834091
Epoch: 18, Loss: 0.08373433351516724
Epoch: 18, Loss: 0.08365699648857117
Epoch: 18, Loss: 0.0835801437497139
Epoch: 18, Loss: 0.08350373804569244
Epoch: 18, Loss: 0.0834278091788292
Epoch: 18, Loss: 0.08335232734680176
Epoch: 18, Loss: 0.08327730000019073
Epoch: 18, Loss: 0.08320271968841553
Epoch: 18, Loss: 0.08312857151031494
Epoch: 18, Loss: 0.08305486291646957
Epoch: 18, Loss: 0.08298160135746002
Epoch: 19, Loss: 0.0829087644815445
Epoch: 19, Loss: 0.0828363448381424
Epoch: 19, Loss: 0.08276434987783432
Epoch: 19, Loss: 0.08269277215003967
Epoch: 19, Loss: 0.08262160420417786
Epoch: 19, Loss: 0.08255085349082947
Epoch: 19, Loss: 0.08248051255941391
Epoch: 19, Loss: 0.08241056650876999
Epoch: 19, Loss: 0.08234100043773651
Epoch: 19, Loss: 0.08227185159921646
Epoch: 19, Loss: 0.08220309019088745
Epoch: 19, Loss: 0.08213470876216888
Epoch: 19, Loss: 0.08206669986248016
Epoch: 19, Loss: 0.08199907839298248
Epoch: 19, Loss: 0.08193184435367584
Epoch: 20, Loss: 0.08186496794223785
Epoch: 20, Loss: 0.08179847151041031
Epoch: 20, Loss: 0.08173232525587082
Epoch: 20, Loss: 0.08166655898094177
Epoch: 20, Loss: 0.08160114288330078
Epoch: 20, Loss: 0.08153608441352844
Epoch: 20, Loss: 0.08147137612104416
Epoch: 20, Loss: 0.08140702545642853
Epoch: 20, Loss: 0.08134301006793976
Epoch: 20, Loss: 0.08127934485673904
Epoch: 20, Loss: 0.08121601492166519
Epoch: 20, Loss: 0.0811530128121376
Epoch: 20, Loss: 0.08109036087989807
Epoch: 20, Loss: 0.0810280367732048
Epoch: 20, Loss: 0.0809660404920578
Epoch: 21, Loss: 0.08090437203645706
Epoch: 21, Loss: 0.0808430090546608
Epoch: 21, Loss: 0.0807819813489914
Epoch: 21, Loss: 0.08072126656770706
Epoch: 21, Loss: 0.0806608647108078
Epoch: 21, Loss: 0.0806007832288742
Epoch: 21, Loss: 0.08054099977016449
Epoch: 21, Loss: 0.08048152178525925
Epoch: 21, Loss: 0.08042236417531967
Epoch: 21, Loss: 0.08036348968744278
Epoch: 21, Loss: 0.08030492812395096
Epoch: 21, Loss: 0.08024665713310242
Epoch: 21, Loss: 0.08018866926431656
Epoch: 21, Loss: 0.08013097941875458
Epoch: 21, Loss: 0.08007358014583588
Epoch: 22, Loss: 0.08001646399497986
Epoch: 22, Loss: 0.07995963096618652
Epoch: 22, Loss: 0.07990308851003647
Epoch: 22, Loss: 0.0798468068242073
Epoch: 22, Loss: 0.07979082316160202
Epoch: 22, Loss: 0.07973508536815643
Epoch: 22, Loss: 0.07967964559793472
Epoch: 22, Loss: 0.07962445914745331
Epoch: 22, Loss: 0.07956955581903458
Epoch: 22, Loss: 0.07951490581035614
Epoch: 22, Loss: 0.07946053147315979
Epoch: 22, Loss: 0.07940640300512314
Epoch: 22, Loss: 0.07935255020856857
Epoch: 22, Loss: 0.0792989432811737
Epoch: 22, Loss: 0.07924558967351913
Epoch: 23, Loss: 0.07919249683618546
Epoch: 23, Loss: 0.07913964986801147
Epoch: 23, Loss: 0.07908705621957779
Epoch: 23, Loss: 0.0790347158908844
Epoch: 23, Loss: 0.07898259907960892
Epoch: 23, Loss: 0.07893074303865433
Epoch: 23, Loss: 0.07887912541627884
Epoch: 23, Loss: 0.07882775366306305
Epoch: 23, Loss: 0.07877659797668457
Epoch: 23, Loss: 0.07872570306062698
Epoch: 23, Loss: 0.0786750391125679
Epoch: 23, Loss: 0.07862458378076553
Epoch: 23, Loss: 0.07857438176870346
Epoch: 23, Loss: 0.0785244032740593
Epoch: 23, Loss: 0.07847464084625244
Epoch: 24, Loss: 0.07842511683702469
Epoch: 24, Loss: 0.07837581634521484
Epoch: 24, Loss: 0.07832672446966171
Epoch: 24, Loss: 0.07827785611152649
Epoch: 24, Loss: 0.07822921127080917
Epoch: 24, Loss: 0.07818079739809036
Epoch: 24, Loss: 0.07813257724046707
Epoch: 24, Loss: 0.07808457314968109
Epoch: 24, Loss: 0.07803679257631302
Epoch: 24, Loss: 0.07798920571804047
Epoch: 24, Loss: 0.07794182747602463
Epoch: 24, Loss: 0.0778946653008461
Epoch: 24, Loss: 0.07784772664308548
Epoch: 24, Loss: 0.07780096679925919
Epoch: 24, Loss: 0.0777544230222702
Epoch: 25, Loss: 0.07770807296037674
Epoch: 25, Loss: 0.0776619240641594
Epoch: 25, Loss: 0.07761597633361816
Epoch: 25, Loss: 0.07757021486759186
Epoch: 25, Loss: 0.07752466946840286
Epoch: 25, Loss: 0.0774793028831482
Epoch: 25, Loss: 0.07743411511182785
Epoch: 25, Loss: 0.07738915085792542
Epoch: 25, Loss: 0.07734435051679611
Epoch: 25, Loss: 0.07729975879192352
Epoch: 25, Loss: 0.07725533843040466
Epoch: 25, Loss: 0.07721111923456192
Epoch: 25, Loss: 0.07716706395149231
Epoch: 25, Loss: 0.07712321728467941
Epoch: 25, Loss: 0.07707952708005905

### Evaluation

In [ ]:
# model evaluation

model.eval()
accuracy_list=[]

with torch.no_grad():
  for batch_features, batch_labels in test_loader:

    # forward pass
    y_pred = model(batch_features)
    y_pred=(y_pred>0.8).float()


    batch_accuracy=(y_pred.view(-1)==batch_labels).float().mean()
    accuracy_list.append(batch_accuracy)

# Overall Accuracy
overall_accuracy=sum(accuracy_list)/len(accuracy_list)
print(f'Accuracy: {overall_accuracy}')

Accuracy: 0.96875